# Generated by Django 4.1.5 on 2023-01-12 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("divulge", "0002_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="fotos_pets")),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("province", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="MZ"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Para adocão"), ("A", "Adotado")],
                        default="p",
                        max_length=1,
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="divulge.breed",
                    ),
                ),
                ("tags", models.ManyToManyField(to="divulge.tag")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
