# Generated by Django 4.1.5 on 2023-01-15 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("divulge", "0003_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="status",
            field=models.CharField(
                choices=[("P", "Para adocão"), ("A", "Adotado")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="AdoptionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AG", "Aguardando aprovação"),
                            ("AP", "Aprovado"),
                            ("R", "Recusado"),
                        ],
                        default="AG",
                        max_length=2,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="divulge.pet"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
